### PR TITLE
Allow comments in authorized_keys files

### PR DESCRIPTION
**Pull request by jochenseeber**
SSH authorized_keys files may contain comments (lines starting with '#'). This PR adds handling for comment lines and also fixes an error with a missing parameter in validate_*_option.

### CODE REVIEW

**Comment by tejaycar** [comment]
So, to be clear,  this is just to prevent the cookbook from stripping out existing comment lines from an existing file?

**Comment by jochenseeber** [comment]
No, it is also because the current implementation crashes when an existing file contains comments. The solution keeps comments in the key file intact.

**Comment by tejaycar** [comment]
@jochenseeber  sorry, I'm pretty swamped right now.  Any chance you can add some tests for this MR?

**Comment by voroniys** [comment]
Please include this MR as soon as possible. You do not need tests for fixing a bug. Current version crashes in file contains comments and this is really annoying.

**Comment by tejaycar** [comment]
@voroniys I appreciate that you have an opinion regarding tests, but I do not merge bug fixes (or any other code) without tests that:
A. reproduce the bug 
AND
B. demonstrate that it is fixed

I do this for two reasons.  First, sometimes a perceived bug isn't actually a bug.  In writing the test, it often exposes the true nature of the bug (or in some cases a simple user error).  Secondly, I want to ensure I don't re-introduce the bug at some future point, and a test will help protect against that.  In fact, I recently make some changes to pull in another PR and they did, in fact, re-introduce a bug that another PR had fixed earlier that day.  Because that fix contained a test, I was able to catch the regression immediately and fix it before releasing the code.

I am going to do what I can to reproduce this and provide a fix.

**Comment by voroniys** [comment]
I would understand your point about testing if it would be recent PR. This one is over half year old! And all this time your cookbook has a nasty bug. I would even say terrible one, because you've also got exception from exception - a double bug! And if you don't trust PR you can reject it - it is your project, but knowing about the bug and doing nothing about this for half year using absence of testing is extremely bad excuse.

Do you know what happens than? The people like me, who needs just working cookbook are using the version of @jochenseeber. It just works and I don't care has it proper testing or not.

And "I'm going to do what I can to reproduce" in this particular cases looks very funny - in half year time you have not found 1 minute of time to add to any authorized_keys file line like
# this is a stupid comment that crashes my cookbook
and run chef-client?

You did a very good job with this cookbook, don't spoil it now! Just find 15 minutes to fix this bug. This is exactly the time I spent for fixing it in the first place, before I went to look on github. But than I've found that here PR for fixing it is waiting for over 6 month for being accepted. Not nice at all.

And if you believe, that test are so important and essential spend another 15 minutes for making a test for it.

**Comment by tejaycar** [comment]
If this bug was causing you so much pain personally, perhaps *you* could
have found 15 minutes to add a test as I asked?  Alternately, remove the
comment from you file.  Welcome to open source software.  I've got a day
job, a family, and a host of other responsibilities.  So, as with all other
open source software, you are free to:
1. Submit a PR that meets the guidelines of the project
2. Fork it
3. Re-write it
4. Use something else

As it stands, I'm currently spending my own personal time to fix a bug that
has not impacted me in the 5 years I've used this cookbook.  Try to show a
little gratitude for a cookbook you didn't have to write yourself.

On Fri, Feb 24, 2017 at 6:37 AM, Stanislav Voroniy <notifications@github.com

**Comment by tejaycar** [comment]
fixed in v0.10.20

**Comment by jochenseeber** [comment]
Sorry, I was completely swamped and had no time to look into unit tests. However, thanks for the merge, and thanks for providing this cookbook.

And @voroniys, the people providing this cookbook have made a valuable contribution to the community. This is their house and their rules. You need not agree, but then you're always free to not use their work.

**Comment by tejaycar** [comment]
Thanks for the kind words Jochen.  Believe me, I know what you mean about
being swamped.  Hence the long delay getting this done.  Thankfully, I have
things in working order again so any new fixes should be pretty quick.

**Pull request closed without merging**
